MACHINES = {
:inetRouter => {
        :net => [
                   {ip: '192.168.255.1', adapter: 2, netmask: "255.255.255.252", virtualbox__intnet: "router-net"},
                   {ip: '192.168.56.10', adapter: 3, netmask: "255.255.255.0"},
                ]
  },
  :inetRouter2 => {
    :net => [
               {ip: '192.168.0.34', adapter: 2, netmask: "255.255.255.240", virtualbox__intnet: "hw-net"},
               {ip: '192.168.56.17', adapter: 3, netmask: "255.255.255.0"},
            ]
  },   
  :centralRouter => {
         :net => [
                   {ip: '192.168.255.2', adapter: 2, netmask: "255.255.255.252", virtualbox__intnet: "router-net"},
                   {ip: '192.168.0.1', adapter: 3, netmask: "255.255.255.240", virtualbox__intnet: "dir-net"},
                   {ip: '192.168.0.33', adapter: 4, netmask: "255.255.255.240", virtualbox__intnet: "hw-net"},
                   {ip: '192.168.0.65', adapter: 5, netmask: "255.255.255.192", virtualbox__intnet: "mgt-net"},
                   {ip: '192.168.255.9', adapter: 6, netmask: "255.255.255.252", virtualbox__intnet: "office1-central"},
                   {ip: '192.168.255.5', adapter: 7, netmask: "255.255.255.252", virtualbox__intnet: "office2-central"},
                   {ip: '192.168.56.11', adapter: 8, netmask: "255.255.255.0"},
                ]
  },
  :centralServer => {
        :net => [
                   {ip: '192.168.0.2', adapter: 2, netmask: "255.255.255.240", virtualbox__intnet: "dir-net"},
                   {ip: '192.168.56.12', adapter: 3, netmask: "255.255.255.0"},
                ]
  },
  :office1Router => {
    :net => [
               {ip: '192.168.255.10', adapter: 2, netmask: "255.255.255.252", virtualbox__intnet: "office1-central"},
               {ip: '192.168.2.1', adapter: 3, netmask: "255.255.255.192", virtualbox__intnet: "dev1-net"},
               {ip: '192.168.2.65', adapter: 4, netmask: "255.255.255.192", virtualbox__intnet: "test1-net"},
               {ip: '192.168.2.129', adapter: 5, netmask: "255.255.255.192", virtualbox__intnet: "managers-net"},
               {ip: '192.168.2.193', adapter: 6, netmask: "255.255.255.192", virtualbox__intnet: "office1-net"},
               {ip: '192.168.56.13', adapter: 7, netmask: "255.255.255.0"},
            ]
  },
    :office1Server => {
        :net => [
                  {ip: '192.168.2.130', adapter: 2, netmask: "255.255.255.192", virtualbox__intnet: "managers-net"},
                  {ip: '192.168.56.14', adapter: 3, netmask: "255.255.255.0"},
                ]
  },
  :office2Router => {
    :net => [
               {ip: '192.168.255.6', adapter: 2, netmask: "255.255.255.252", virtualbox__intnet: "office2-central"},
               {ip: '192.168.1.1', adapter: 3, netmask: "255.255.255.128", virtualbox__intnet: "dev2-net"},
               {ip: '192.168.1.129', adapter: 4, netmask: "255.255.255.192", virtualbox__intnet: "test2-net"},
               {ip: '192.168.1.193', adapter: 5, netmask: "255.255.255.192", virtualbox__intnet: "office2-net"},
               {ip: '192.168.56.15', adapter: 6, netmask: "255.255.255.0"},
            ]
},
  :office2Server => {
      :net => [
                {ip: '192.168.1.2', adapter: 2, netmask: "255.255.255.128", virtualbox__intnet: "dev2-net"},
                {ip: '192.168.56.16', adapter: 3, netmask: "255.255.255.0"},
              ]
  }
}

Vagrant.configure("2") do |config|
  MACHINES.each do |boxname, boxconfig|
    config.vbguest.auto_update = false
    config.vm.define boxname do |box|
      box.vm.box = "lvv321/Ubuntu22.4"
      box.vm.box_version = "1.1"
      box.vm.hostname = boxname.to_s
      box.vm.provider "virtualbox" do |v|
        v.check_guest_additions = false
        v.cpus = 2
        v.customize ["modifyvm", :id, "--nested-paging", "on"]
        v.customize ["modifyvm", :id, "--paravirt-provider", "hyperv"]
        v.memory = 1024
        v.name = boxname.to_s
      end
      boxconfig[:net].each do |ipconf|
        box.vm.network "private_network", ip: ipconf[:ip], adapter: ipconf[:adapter], netmask: ipconf[:netmask], virtualbox__intnet: ipconf[:virtualbox__intnet]
      end
      if boxname.to_s == "office2Server"
        box.vm.provision "ansible" do |ansible|
         ansible.playbook = "Ansible/provision.yml"
         ansible.inventory_path = "Ansible/hosts"
         ansible.host_key_checking = "false"
         ansible.limit = "all"
        end
       end
    end
  end
end

