# -*- mode: ruby -*-
# vi: set ft=ruby :
# export VAGRANT_EXPERIMENTAL="disks"

Vagrant.configure("2") do |config|

config.vm.define "pxeserver" do |server|
  server.vbguest.auto_update = false
  server.vm.box = 'bento/centos-8.4'
  #server.vm.disk :disk, size: "15GB", name: "extra_storage1"

  server.vm.host_name = 'pxeserver'
  server.vm.network :private_network, 
                     ip: "10.0.0.20", 
                     virtualbox__intnet: 'pxenet'
  server.vm.network :private_network,
                     ip: "192.168.56.10", adapter: 3

  # server.vm.network "forwarded_port", guest: 80, host: 8081

  server.vm.provider "virtualbox" do |vb|
    vb.check_guest_additions = false
    vb.customize ["modifyvm", :id, "--nested-paging", "off"]
    vb.customize ["modifyvm", :id, "--paravirt-provider", "hyperv"]
    vb.memory = "1024"
    vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
  end

  # ENABLE to setup PXE
  #server.vm.provision "shell",
  #  name: "Setup PXE server",
  #  path: "setup_pxe.sh"

  server.vm.provision "ansible" do |ansible|
    ansible.playbook = "Ansible/provision.yml"
    ansible.inventory_path = "Ansible/hosts"
    ansible.host_key_checking = "false"
    ansible.limit = "all"
  end
  
end


# config used from this
# https://github.com/eoli3n/vagrant-pxe/blob/master/client/Vagrantfile
  config.vm.define "pxeclient" do |pxeclient|
    pxeclient.vbguest.auto_update = false
    pxeclient.vm.box = 'bento/centos-8.4'
    pxeclient.vm.host_name = 'pxeclient'
    pxeclient.vm.network :private_network, 
                          ip: "10.0.0.21", 
                          virtualbox__intnet: 'pxenet'
    pxeclient.vm.provider :virtualbox do |vb|
      vb.check_guest_additions = false
      vb.memory = "2048"
      vb.customize ["modifyvm", :id, "--natdnshostresolver1", "off"]
      vb.customize ["modifyvm", :id, "--nested-paging", "on"]
      vb.customize ["modifyvm", :id, "--paravirt-provider", "hyperv"]
      vb.customize [
          'modifyvm', :id,
          '--nic1', 'intnet',
          '--intnet1', 'pxenet',
          '--nic2', 'nat',
          '--boot1', 'net',
          '--boot2', 'none',
          '--boot3', 'none',
          '--boot4', 'none'
        ]
    vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
    end
      # ENABLE to fix memory issues
#     end
  end

end
