---
- name: setup network lab
  hosts: all
  become: yes
  tasks:
    - name: install soft
      apt:
        name:
          - traceroute
        state: present
        update_cache: true

    - name: install soft on inetRouter
      apt:
        name:
          - ifupdown
        state: present
        update_cache: true
      when: (ansible_hostname == "inetRouter")

    - name: setup forward packages across routers
      sysctl:
        name: net.ipv4.conf.all.forwarding
        value: '1'
        state: present
      when: "'routers' in group_names"

    - name: setup NAT on inetRouter
      template: 
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        owner: root
        group: root
        mode: "{{ item.mode }}"
      with_items:
        - { src: "iptables_rules.ipv4", dest: "/etc/iptables_rules.ipv4", mode: "0644" }
        - { src: "iptables_restore", dest: "/etc/network/if-pre-up.d/iptables", mode: "0755" }
      when: (ansible_hostname == "inetRouter")

    - name: disable default route
      template: 
        src: 00-installer-config.yaml
        dest: /etc/netplan/00-installer-config.yaml
        owner: root
        group: root
        mode: 0644
      when: (ansible_hostname != "inetRouter") 

    - name: add default gateway and routes
      template: 
        src: "50-vagrant_{{ansible_hostname}}.yaml"
        dest: /etc/netplan/50-vagrant.yaml
        owner: root
        group: root
        mode: 0644

    - name: restart all hosts
      reboot:
        reboot_timeout: 600
