MACHINES = {
  :inetRouter => {
    :net => [
              {ip: "10.10.10.10", netmask: "255.0.0.0", adapter: 2, auto_config: false, virtualbox__intnet: "router-net"},
              {ip: "10.10.10.10", netmask: "255.0.0.0", adapter: 3, auto_config: false, virtualbox__intnet: "router-net"},
              {ip: '192.168.56.10', adapter: 8, netmask: "255.255.255.0", auto_config: true},
            ]
  },
  :centralRouter => {
    :net => [
              {ip: "10.10.10.10", netmask: "255.0.0.0", adapter: 2, auto_config: false, virtualbox__intnet: "router-net"},
              {ip: "10.10.10.10", netmask: "255.0.0.0", adapter: 3, auto_config: false, virtualbox__intnet: "router-net"},
              {ip: '192.168.255.9', adapter: 4, netmask: "255.255.255.252", virtualbox__intnet: "office1-central", auto_config: true},
              {ip: '192.168.56.11', adapter: 8, netmask: "255.255.255.0", auto_config: true},
            ]
  },
  :office1Router => {
    :net => [
              {ip: '192.168.255.10', adapter: 2, netmask: "255.255.255.252", virtualbox__intnet: "office1-central", auto_config: true},
              {ip: "10.10.10.10", netmask: "255.0.0.0", adapter: 3, auto_config: false, virtualbox__intnet: "vlan1"},
              {ip: "10.10.10.10", netmask: "255.0.0.0", adapter: 4, auto_config: false, virtualbox__intnet: "vlan1"},
              {ip: "10.10.10.10", netmask: "255.0.0.0", adapter: 5, auto_config: false, virtualbox__intnet: "vlan2"},
              {ip: "10.10.10.10", netmask: "255.0.0.0", adapter: 6, auto_config: false, virtualbox__intnet: "vlan2"},
              {ip: '192.168.56.12', adapter: 8, netmask: "255.255.255.0", auto_config: true},
            ]
  },
  :testClient1 => {
    :net => [
              {ip: "10.10.10.10", netmask: "255.0.0.0", adapter: 2, auto_config: false, virtualbox__intnet: "testLAN"},
              {ip: '192.168.56.13', adapter: 8, netmask: "255.255.255.0", auto_config: true},
            ]
  },
  :testServer1 => {
    :net => [
              {ip: "10.10.10.10", netmask: "255.0.0.0", adapter: 2, auto_config: false, virtualbox__intnet: "testLAN"},
              {ip: '192.168.56.14', adapter: 8, netmask: "255.255.255.0", auto_config: true},
            ]
  },
  :testClient2 => {
    :net => [
              {ip: "10.10.10.10", netmask: "255.0.0.0", adapter: 2, auto_config: false, virtualbox__intnet: "testLAN"},
              {ip: '192.168.56.15', adapter: 8, netmask: "255.255.255.0", auto_config: true},
            ]
  },
  :testServer2 => {
    :net => [
              {ip: "10.10.10.10", netmask: "255.0.0.0", adapter: 2, auto_config: false, virtualbox__intnet: "testLAN"},
              {ip: '192.168.56.16', adapter: 8, netmask: "255.255.255.0", auto_config: true},
            ]
  }
}

Vagrant.configure("2") do |config|
  MACHINES.each do |boxname, boxconfig|
    config.vbguest.auto_update = false
    config.vm.define boxname do |box|
      box.vm.box = "lvv321/Ubuntu22.4"
      box.vm.box_version = "1.1"
      box.vm.hostname = boxname.to_s
      box.vm.provider "virtualbox" do |v|
        v.check_guest_additions = false
        v.cpus = 2
        v.customize ["modifyvm", :id, "--nested-paging", "on"]
        v.customize ["modifyvm", :id, "--paravirt-provider", "hyperv"]
        v.memory = 1024
        v.name = boxname.to_s
      end
      boxconfig[:net].each do |ipconf|
        box.vm.network "private_network", auto_config: ipconf[:auto_config], ip: ipconf[:ip], adapter: ipconf[:adapter], netmask: ipconf[:netmask], virtualbox__intnet: ipconf[:virtualbox__intnet]
      end 
      if boxname.to_s == "testServer2"
        box.vm.provision "ansible" do |ansible|
         ansible.playbook = "Ansible/provision.yml"
         ansible.inventory_path = "Ansible/hosts"
         ansible.host_key_checking = "false"
         ansible.limit = "all"
        end
       end
    end
  end
end

