MACHINES = {
  :"myvm" => {
    :box_name => "lvv321/Ubuntu22.4",
    :box_version => "1.1",
  :cpus => 2,
  :memory => 2048
  }
}

Vagrant.configure("2") do |config|
  MACHINES.each do |boxname, boxconfig|
    config.vm.define boxname do |box|
      box.vm.box = boxconfig[:box_name]
      box.vm.box_version = boxconfig[:box_version]
      box.vm.provider "virtualbox" do |v|
        v.cpus = boxconfig[:cpus]
        v.customize ["modifyvm", :id, "--nested-paging", "on"]
        v.customize ["modifyvm", :id, "--paravirt-provider", "hyperv"]
        v.memory = boxconfig[:memory]
        v.name = boxname.to_s
      end
      box.vm.hostname = boxname.to_s
    end
    config.vm.synced_folder ".", "/vagrant", disabled: true
  end
end
