MACHINES = {
  :"my-machine" => {
              :box_name => "lvv321/Ubuntu22.4",
              :box_version => "1.0",
            }
}

Vagrant.configure("2") do |config|
  MACHINES.each do |boxname, boxconfig|
    config.vm.synced_folder ".", "/vagrant", disabled: true
    config.vm.define boxname do |box|
      box.vm.box = boxconfig[:box_name]
      box.vm.box_version = boxconfig[:box_version]
      box.vm.host_name = boxname.to_s
      box.vm.provider "virtualbox" do |v|
        v.customize ["modifyvm", :id, "--paravirt-provider", "hyperv"]
      end
    end
  end
end