MACHINES = {
  :router1 => {
    :net => [
      {ip: '10.0.10.1', adapter: 2, netmask: "255.255.255.252", virtualbox__intnet: "r1-r2"},
      {ip: '10.0.12.1', adapter: 3, netmask: "255.255.255.252", virtualbox__intnet: "r1-r3"},
      {ip: '192.168.10.1', adapter: 4, netmask: "255.255.255.0", virtualbox__intnet: "net1"},
      {ip: '192.168.56.10', adapter: 5, netmask: "255.255.255.0"},
    ]
  },
  :router2 => {
    :net => [
      {ip: '10.0.10.2', adapter: 2, netmask: "255.255.255.252", virtualbox__intnet: "r1-r2"},
      {ip: '10.0.11.2', adapter: 3, netmask: "255.255.255.252", virtualbox__intnet: "r2-r3"},
      {ip: '192.168.20.1', adapter: 4, netmask: "255.255.255.0", virtualbox__intnet: "net2"},
      {ip: '192.168.56.11', adapter: 5, netmask: "255.255.255.0"},
    ]
  },   
  :router3 => {
    :net => [
      {ip: '10.0.11.1', adapter: 2, netmask: "255.255.255.252", virtualbox__intnet: "r2-r3"},
      {ip: '10.0.12.2', adapter: 3, netmask: "255.255.255.252", virtualbox__intnet: "r1-r3"},
      {ip: '192.168.30.1', adapter: 4, netmask: "255.255.255.0", virtualbox__intnet: "net3"},
      {ip: '192.168.56.12', adapter: 5, netmask: "255.255.255.0"},
    ]
  }
}

Vagrant.configure("2") do |config|
  MACHINES.each do |boxname, boxconfig|
    config.vbguest.auto_update = false
    config.vm.define boxname do |box|
      box.vm.box = "lvv321/Ubuntu22.4"
      box.vm.box_version = "1.1"
      box.vm.hostname = boxname.to_s
      box.vm.provider "virtualbox" do |v|
        v.check_guest_additions = false
        v.cpus = 2
        v.customize ["modifyvm", :id, "--nested-paging", "on"]
        v.customize ["modifyvm", :id, "--paravirt-provider", "hyperv"]
        v.memory = 1024
        v.name = boxname.to_s
      end
      boxconfig[:net].each do |ipconf|
        box.vm.network "private_network", ip: ipconf[:ip], adapter: ipconf[:adapter], netmask: ipconf[:netmask], virtualbox__intnet: ipconf[:virtualbox__intnet]
      end
      if boxname.to_s == "router3"
        box.vm.provision "ansible" do |ansible|
          ansible.playbook = "Ansible/provision.yml"
          ansible.inventory_path = "Ansible/hosts"
          ansible.host_key_checking = "false"
          ansible.limit = "all"
        end
      end
    end
  end
end

