---
- name: setup VPN
  hosts: all
  become: yes
  
  vars_files:
    - defaults/main.yml
  
  tasks:
    - name: install soft
      apt:
        name:
          - openvpn
          - iperf3
        state: present
        update_cache: true

    - name: generate the key
      command:
        cmd: openvpn --genkey secret /etc/openvpn/static.key
        creates: /etc/openvpn/static.key
      when: (ansible_hostname == "server")

    - name: fetch the key from server to tmp
      run_once: yes
      fetch:
        src: /etc/openvpn/static.key
        dest: buffer/static.key
        flat: yes
      when: (ansible_hostname == "server")

    - name: copy the key from tmp to client
      copy:
        src: buffer/static.key
        dest: /etc/openvpn/static.key
      when: (ansible_hostname == "client")

    - name: create openvpn config
      template:
        src: openvpn_{{ansible_hostname}}.conf
        dest: /etc/openvpn/server.conf
        owner: root
        group: root
        mode: 0640

    - name: create service unit
      template:
        src: openvpn@.service
        dest: /etc/systemd/system/openvpn@.service
        owner: root
        group: root
        mode: 0640

    - name: start openvpn@server
      service:
        name: openvpn@server
        state: started
        enabled: true
