MACHINES = {
  :"server.mylab.local" => {
    :net => [
      {ip: '192.168.56.10', adapter: 2, netmask: "255.255.255.0"},
    ]
  },
  :"client.mylab.local" => {
    :net => [
      {ip: '192.168.56.20', adapter: 2, netmask: "255.255.255.0"},
    ]
  }   
}

Vagrant.configure("2") do |config|
  MACHINES.each do |boxname, boxconfig|
    config.vbguest.auto_update = false
    config.vm.define boxname do |box|
      box.vm.box = "generic/centos8"
      box.vm.hostname = boxname.to_s
      box.vm.provider "virtualbox" do |v|
        v.check_guest_additions = false
        v.cpus = 4
        v.customize ["modifyvm", :id, "--nested-paging", "off"]
        v.customize ["modifyvm", :id, "--paravirt-provider", "hyperv"]
        v.memory = 4096
        v.name = boxname.to_s
      end
      boxconfig[:net].each do |ipconf|
        box.vm.network "private_network", ip: ipconf[:ip], adapter: ipconf[:adapter], netmask: ipconf[:netmask], virtualbox__intnet: ipconf[:virtualbox__intnet]
      end
      if boxname.to_s == "client.mylab.local"
        box.vm.provision "ansible" do |ansible|
          ansible.playbook = "Ansible/provision.yml"
          ansible.inventory_path = "Ansible/hosts"
          ansible.host_key_checking = "false"
          ansible.limit = "all"
        end
      end
    end
  end
end

