MACHINES = {
  :"myvm" => {
    :box_name => "lvv321/Ubuntu22.4",
    :box_version => "1.1",
    :disks => {
      :sata1 => {
        :dfile => './sata1.vdi',
        :size => 250,
        :port => 1
      },
      :sata2 => {
        :dfile => './sata2.vdi',
        :size => 250,
        :port => 2
      },
      :sata3 => {
        :dfile => './sata3.vdi',
        :size => 250,
        :port => 3
      },
      :sata4 => {
        :dfile => './sata4.vdi',
        :size => 250,
        :port => 4
      },
      :sata5 => {
        :dfile => './sata5.vdi',
        :size => 250,
        :port => 5
      }
    },
  :cpus => 2,
  :memory => 2048
  }
}

Vagrant.configure("2") do |config|
  MACHINES.each do |boxname, boxconfig|
    config.vm.define boxname do |box|
      box.vm.box = boxconfig[:box_name]
      box.vm.box_version = boxconfig[:box_version]
      box.vm.hostname = boxname.to_s
      box.vm.provider "virtualbox" do |v|
        boxconfig[:disks].each do |dname, dconf|
          unless File.exist?(dconf[:dfile])
            v.customize ['createhd', '--filename', dconf[:dfile], '--variant', 'Fixed', '--size', dconf[:size]]
          end
          v.customize ['storageattach', :id, '--storagectl', 'SATA Controller', '--port', dconf[:port], '--device', 0, '--type', 'hdd', '--medium', dconf[:dfile]]
        end
        v.cpus = boxconfig[:cpus]
        v.customize ["modifyvm", :id, "--nested-paging", "on"]
        v.customize ["modifyvm", :id, "--paravirt-provider", "hyperv"]
        v.memory = boxconfig[:memory]
        v.name = boxname.to_s
      end
      box.vm.provision "shell", path: "./config_disk.sh"
    end
    config.vm.synced_folder ".", "/vagrant", disabled: true
  end
end
